-- 멤버십 주요 사용처 / 공식 사이트 시드.
-- 프론트 utils(partnerUsagePlaces.js, partnerSites.js)에 하드코딩돼 있던 값을 DB로 옮긴 것이다.
-- 이 파일은 스크립트로 생성했다. 값을 고칠 때는 여기를 직접 고친다(유틸 파일은 삭제 예정).
-- 실행 순서: schema.sql -> 91 -> 92 -> 94

-- 1) 공식 사이트 URL 컬럼. point_provider 에는 URL을 담을 자리가 없었다.
--    제휴사 로그인 URL은 OAuth 파라미터가 통째로 붙는 경우가 있다.
--    현재 최장은 뷰티포인트 1157자라 500자로는 잘린다. 여유를 두고 1500으로 잡는다.
ALTER TABLE point_provider
    ADD COLUMN official_site_url VARCHAR(1500) NULL COMMENT '공식 사이트 URL' AFTER logo_image_url;

-- 2) 공식 사이트 URL 채우기
UPDATE point_provider SET official_site_url = 'https://www.cjone.com/cjmweb/login.do' WHERE point_provider_id = 3;
UPDATE point_provider SET official_site_url = 'https://www.happypointcard.com/sso/login.jsp?returnUrl=/page/presentation/membership.spc' WHERE point_provider_id = 4;
UPDATE point_provider SET official_site_url = 'https://m.lpoint.com/app/login/LWLA100100.do' WHERE point_provider_id = 7;
UPDATE point_provider SET official_site_url = 'https://www.shinsegae.com/service/membership/shinsegae-point.do' WHERE point_provider_id = 8;
UPDATE point_provider SET official_site_url = 'https://h-point.co.kr/cu/login.nhd' WHERE point_provider_id = 9;
UPDATE point_provider SET official_site_url = 'https://www.okcashbag.com/login' WHERE point_provider_id = 10;
UPDATE point_provider SET official_site_url = 'https://www.gsall.com/gsallpoint.html' WHERE point_provider_id = 11;
UPDATE point_provider SET official_site_url = 'https://www.elandretail.com/m/epoint/Integrate_Account1.do' WHERE point_provider_id = 12;
UPDATE point_provider SET official_site_url = 'https://www.nhmembers.co.kr/nhweb/join/joinMbSelectCert.nh' WHERE point_provider_id = 13;
UPDATE point_provider SET official_site_url = 'https://one-ap.amorepacific.com/auth/login?channelCd=030&cid=1836821967.1785287602&client_id=HkJyP7_EGWntx06NtszdlhWO8vAa&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Fwww.beautypoint.co.kr%2Fapi%2Foauth2client&response_type=code&scope=openid&sid=s1785744992%24o2%24g1%24t1785744997%24j55%24l0%24h0&state=%7BredirectUri%3Dhttps%3A%2F%2Fwww.beautypoint.co.kr%2Fapi%2Flogin%3FreturnUrl%3Dhttps%3A%2F%2Fwww.beautypoint.co.kr%2Ffo-api%2Flogin%2FeyJyZWRpcmVjdFVybCI6Imh0dHBzOi8vd3d3LmJlYXV0eXBvaW50LmNvLmtyL21lbWJlcnNoaXAiLCJzZXNzaW9uSWQiOiIifQ%3D%3D%2C+gid%3Dnull%2C+channelCd%3D030%2C+ot%3Dnull%2C+sid%3Ds1785744992%24o2%24g1%24t1785744997%24j55%24l0%24h0%2C+dt%3Dnull%2C+popup%3Dnull%2C+cancelUri%3D%2C+kakaoEmbedded%3Dnull%2C+join%3Dnull%2C+prompt%3Dnull%2C+vt%3Dnull%2C+cid%3D1836821967.1785287602%7D&sessionDataKey=89f75dfa-b077-4172-9e90-31f475ae9393&relyingParty=HkJyP7_EGWntx06NtszdlhWO8vAa&type=oidc&sp=030&spId=cfbe4ea9-4aad-4e9e-b6be-188aa27ee1d4&isSaaSApp=false&authenticators=NAVER%3ANA%3BKAKAO%3AKA%3BAppleID%3AAP%3BMobileVerifier%3ALOCAL%3BBasicAuthenticator%3ALOCAL%3BISKVerifier%3ALOCAL' WHERE point_provider_id = 14;
UPDATE point_provider SET official_site_url = 'https://shop.tworld.co.kr/exhibition/view?exhibitionId=P00000494&utm_source=tworld&utm_medium=pc_banner&utm_campaign=foldable8' WHERE point_provider_id = 15;
UPDATE point_provider SET official_site_url = 'https://shop.tworld.co.kr/exhibition/view?exhibitionId=P00000494&utm_source=tworld&utm_medium=pc_banner&utm_campaign=foldable8' WHERE point_provider_id = 16;
UPDATE point_provider SET official_site_url = 'https://account.lguplus.com/login?client_id=G8RoYUvnwILirwwwK3xG4WR8q9D83to7&login_type=STANDARD_WEB&prompt=select_account&i18nextLng=ko' WHERE point_provider_id = 17;
UPDATE point_provider SET official_site_url = 'https://nid.naver.com/membership/join' WHERE point_provider_id = 18;
UPDATE point_provider SET official_site_url = 'https://www.payco.com/' WHERE point_provider_id = 19;
UPDATE point_provider SET official_site_url = 'https://m.ssfshop.com/public/member/addMemberStep1' WHERE point_provider_id = 20;
UPDATE point_provider SET official_site_url = 'https://www.lfmembers.co.kr:4441/web/index.do' WHERE point_provider_id = 21;
UPDATE point_provider SET official_site_url = 'https://m.thehandsome.com/ko/MK/event/24743' WHERE point_provider_id = 22;
UPDATE point_provider SET official_site_url = 'https://idpconnect-kr.hyundai.com/auth/api/v2/user/oauth2/authorize?client_id=2b6b3d2d-5ccc-497f-8e8b-e9b2d7582097&redirect_uri=https%3A%2F%2Fwww.hyundai.com%2Fkr%2Fko%2Fccspcallback.html%3Fhmgid%3D2&response_type=code&scope=&state=login&connector_client_id=hmgid1.0-2b6b3d2d-5ccc-497f-8e8b-e9b2d7582097&ui_locales=&connector_scope=&connector_session_key=3dba3d13-92ad-4c72-acc3-462184770a7f' WHERE point_provider_id = 23;
UPDATE point_provider SET official_site_url = 'https://idpconnect-kr.kia.com/auth/api/v2/user/oauth2/authorize?client_id=8a98de01-a5ca-442a-a4aa-9127647f9c7b&redirect_uri=https%3A%2F%2Fmembers.kia.com%2Fkr%2Fview%2Fhmgidredirect.do&response_type=code&scope=&state=1&connector_client_id=hmgid1.0-8a98de01-a5ca-442a-a4aa-9127647f9c7b&ui_locales=&connector_scope=&connector_session_key=f1026214-d10b-4dce-a750-9a941f79e63d' WHERE point_provider_id = 24;

-- 3) 주요 사용처. 재실행해도 중복이 쌓이지 않도록 해당 제공사 행을 먼저 지운다.
DELETE FROM point_usage_place WHERE point_provider_id IN (3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24);

INSERT INTO point_usage_place (point_provider_id, place_name, use_yn) VALUES
    (3, 'CGV', 'Y'),
    (3, '올리브영', 'Y'),
    (3, 'CJ더마켓', 'Y'),
    (3, '뚜레쥬르', 'Y'),
    (3, 'VIPS', 'Y'),
    (3, '더플레이스', 'Y'),
    (3, '제일제면소', 'Y'),
    (3, 'N서울타워', 'Y'),
    (3, 'CJ온스타일', 'Y'),
    (3, 'TVING', 'Y'),
    (3, '메가MGC커피', 'Y'),
    (3, 'CU', 'Y'),
    (4, '파리바게뜨', 'Y'),
    (4, '배스킨라빈스', 'Y'),
    (4, '던킨', 'Y'),
    (4, '파스쿠찌', 'Y'),
    (4, '쉐이크쉑', 'Y'),
    (4, '파리크라상', 'Y'),
    (4, '빚은', 'Y'),
    (4, '라그릴리아', 'Y'),
    (4, '패션5', 'Y'),
    (4, '리나스', 'Y'),
    (4, '커피앳웍스', 'Y'),
    (4, '리안헤어', 'Y'),
    (7, '롯데백화점', 'Y'),
    (7, '롯데마트', 'Y'),
    (7, '롯데슈퍼', 'Y'),
    (7, '롯데ON', 'Y'),
    (7, '롯데시네마', 'Y'),
    (7, '세븐일레븐', 'Y'),
    (7, '롯데리아', 'Y'),
    (7, '엔제리너스', 'Y'),
    (7, '크리스피크림도넛', 'Y'),
    (7, '롯데월드', 'Y'),
    (7, '롯데호텔', 'Y'),
    (7, 'S-OIL', 'Y'),
    (8, '신세계백화점', 'Y'),
    (8, '이마트', 'Y'),
    (8, 'SSG.COM', 'Y'),
    (8, '이마트24', 'Y'),
    (8, '스타벅스', 'Y'),
    (8, '신세계면세점', 'Y'),
    (8, '조선호텔앤리조트', 'Y'),
    (8, '스타필드', 'Y'),
    (8, '신세계사이먼 프리미엄아울렛', 'Y'),
    (8, '노브랜드', 'Y'),
    (8, '일렉트로마트', 'Y'),
    (8, '트레이더스 홀세일 클럽', 'Y'),
    (9, '현대백화점', 'Y'),
    (9, '더현대닷컴', 'Y'),
    (9, '현대홈쇼핑', 'Y'),
    (9, '현대Hmall', 'Y'),
    (9, '현대백화점면세점', 'Y'),
    (9, '현대식품관 투홈', 'Y'),
    (9, '한섬', 'Y'),
    (9, '더한섬닷컴', 'Y'),
    (9, '현대리바트', 'Y'),
    (9, '리바트몰', 'Y'),
    (9, '현대렌탈케어', 'Y'),
    (9, '현대드림투어', 'Y'),
    (10, '11번가', 'Y'),
    (10, 'SK에너지', 'Y'),
    (10, '세븐일레븐', 'Y'),
    (10, 'CU', 'Y'),
    (10, '이마트24', 'Y'),
    (10, '홈플러스', 'Y'),
    (10, '롯데리아', 'Y'),
    (10, '도미노피자', 'Y'),
    (10, '파리바게뜨', 'Y'),
    (10, '배스킨라빈스', 'Y'),
    (10, '메가박스', 'Y'),
    (10, 'YES24', 'Y'),
    (11, 'GS25', 'Y'),
    (11, 'GS SHOP', 'Y'),
    (11, 'GS더프레시', 'Y'),
    (11, '우리동네GS', 'Y'),
    (11, 'GS Postbox', 'Y'),
    (11, '와인25플러스', 'Y'),
    (11, '쿠캣', 'Y'),
    (11, 'GS Pay', 'Y'),
    (11, 'GS리테일 행사상품', 'Y'),
    (11, 'GS25 택배', 'Y'),
    (11, 'GS THE FRESH 온라인몰', 'Y'),
    (11, 'GS SHOP 모바일앱', 'Y'),
    (12, '이랜드몰', 'Y'),
    (12, 'NC백화점', 'Y'),
    (12, '뉴코아아울렛', 'Y'),
    (12, '동아백화점', 'Y'),
    (12, '킴스클럽', 'Y'),
    (12, '스파오', 'Y'),
    (12, '미쏘', 'Y'),
    (12, '후아유', 'Y'),
    (12, '로엠', 'Y'),
    (12, '슈펜', 'Y'),
    (12, '폴더', 'Y'),
    (12, '애슐리', 'Y'),
    (13, '농협하나로마트', 'Y'),
    (13, '농협몰', 'Y'),
    (13, 'NH농협은행', 'Y'),
    (13, 'NH농협카드', 'Y'),
    (13, 'NH투자증권', 'Y'),
    (13, 'NH농협생명', 'Y'),
    (13, 'NH농협손해보험', 'Y'),
    (13, '농협주유소', 'Y'),
    (13, 'NH포인트샵', 'Y'),
    (13, '한삼인', 'Y'),
    (13, '목우촌', 'Y'),
    (13, '농협축산물프라자', 'Y'),
    (14, '아모레몰', 'Y'),
    (14, '아리따움', 'Y'),
    (14, '이니스프리', 'Y'),
    (14, '에뛰드', 'Y'),
    (14, '설화수', 'Y'),
    (14, '헤라', 'Y'),
    (14, '아이오페', 'Y'),
    (14, '라네즈', 'Y'),
    (14, '마몽드', 'Y'),
    (14, '한율', 'Y'),
    (14, '프리메라', 'Y'),
    (14, '에스트라', 'Y'),
    (15, '파리바게뜨', 'Y'),
    (15, '파리크라상', 'Y'),
    (15, '뚜레쥬르', 'Y'),
    (15, 'VIPS', 'Y'),
    (15, '던킨', 'Y'),
    (15, '배스킨라빈스', 'Y'),
    (15, '세븐일레븐', 'Y'),
    (15, 'CU', 'Y'),
    (15, 'CGV', 'Y'),
    (15, '롯데시네마', 'Y'),
    (15, '메가박스', 'Y'),
    (15, '11번가', 'Y'),
    (16, '파리바게뜨', 'Y'),
    (16, '파리크라상', 'Y'),
    (16, '뚜레쥬르', 'Y'),
    (16, 'VIPS', 'Y'),
    (16, '던킨', 'Y'),
    (16, '배스킨라빈스', 'Y'),
    (16, '세븐일레븐', 'Y'),
    (16, 'CU', 'Y'),
    (16, 'CGV', 'Y'),
    (16, '롯데시네마', 'Y'),
    (16, '메가박스', 'Y'),
    (16, '11번가', 'Y'),
    (17, '파리바게뜨', 'Y'),
    (17, '배스킨라빈스', 'Y'),
    (17, 'GS25', 'Y'),
    (17, 'CGV', 'Y'),
    (17, '메가박스', 'Y'),
    (17, '롯데시네마', 'Y'),
    (17, '도미노피자', 'Y'),
    (17, 'VIPS', 'Y'),
    (17, '아웃백', 'Y'),
    (17, '일리커피', 'Y'),
    (17, '프린트베이커리', 'Y'),
    (17, '야놀자', 'Y'),
    (18, '네이버플러스 스토어', 'Y'),
    (18, '네이버쇼핑', 'Y'),
    (18, '네이버 브랜드스토어', 'Y'),
    (18, '네이버예약', 'Y'),
    (18, '네이버여행', 'Y'),
    (18, '네이버장보기', 'Y'),
    (18, '네이버웹툰', 'Y'),
    (18, '네이버시리즈', 'Y'),
    (18, '티빙', 'Y'),
    (18, '요기요', 'Y'),
    (18, '네이버페이', 'Y'),
    (18, '네이버 MY플레이스', 'Y'),
    (19, 'PAYCO 온라인결제', 'Y'),
    (19, 'PAYCO 오프라인결제', 'Y'),
    (19, 'PAYCO 포인트카드', 'Y'),
    (19, '컬처랜드', 'Y'),
    (19, '티머니', 'Y'),
    (19, '이즐', 'Y'),
    (19, 'GS25', 'Y'),
    (19, 'CU', 'Y'),
    (19, '세븐일레븐', 'Y'),
    (19, '이마트24', 'Y'),
    (19, '배달의민족', 'Y'),
    (19, '요기요', 'Y'),
    (20, 'SSF SHOP', 'Y'),
    (20, '갤럭시', 'Y'),
    (20, '로가디스', 'Y'),
    (20, '빈폴', 'Y'),
    (20, '에잇세컨즈', 'Y'),
    (20, '구호', 'Y'),
    (20, '구호플러스', 'Y'),
    (20, '르베이지', 'Y'),
    (20, '비이커', 'Y'),
    (20, '준지', 'Y'),
    (20, '띠어리', 'Y'),
    (20, '메종키츠네', 'Y'),
    (21, 'LF몰', 'Y'),
    (21, '헤지스', 'Y'),
    (21, '닥스', 'Y'),
    (21, '질스튜어트뉴욕', 'Y'),
    (21, '마에스트로', 'Y'),
    (21, '알레그리', 'Y'),
    (21, 'TNGT', 'Y'),
    (21, '라푸마', 'Y'),
    (21, '리복', 'Y'),
    (21, '챔피온', 'Y'),
    (21, '바버', 'Y'),
    (21, '아떼', 'Y'),
    (22, '더한섬닷컴', 'Y'),
    (22, 'TIME', 'Y'),
    (22, 'MINE', 'Y'),
    (22, 'SYSTEM', 'Y'),
    (22, 'SJSJ', 'Y'),
    (22, 'TIME HOMME', 'Y'),
    (22, 'SYSTEM HOMME', 'Y'),
    (22, 'the CASHMERE', 'Y'),
    (22, 'LÄTT', 'Y'),
    (22, 'O''2nd', 'Y'),
    (22, 'DECKE', 'Y'),
    (22, 'TOM GREYHOUND', 'Y'),
    (23, '블루핸즈', 'Y'),
    (23, '현대자동차', 'Y'),
    (23, '현대 Shop', 'Y'),
    (23, '현대 디지털키', 'Y'),
    (23, '카앤라이프몰', 'Y'),
    (23, '현대모비스', 'Y'),
    (23, '현대오일뱅크', 'Y'),
    (23, '해비치호텔앤드리조트', 'Y'),
    (23, '오토앤', 'Y'),
    (23, '현대셀렉션', 'Y'),
    (23, 'H Genuine Accessories', 'Y'),
    (23, '마이현대', 'Y'),
    (24, '오토큐', 'Y'),
    (24, '기아자동차', 'Y'),
    (24, '기아멤버스몰', 'Y'),
    (24, '기아커넥트', 'Y'),
    (24, '기아 디지털키', 'Y'),
    (24, '기아 EV 충전', 'Y'),
    (24, '현대모비스', 'Y'),
    (24, '오토앤', 'Y'),
    (24, '카앤라이프몰', 'Y'),
    (24, 'GS칼텍스', 'Y'),
    (24, '해비치호텔앤드리조트', 'Y'),
    (24, '마이기아', 'Y');
